### PR TITLE
docs: Create pull_request_template.md

### PR DESCRIPTION
**Pull request by jlkravitz**
This is the template for PRs, for us and for the outside world (to, e.g., add models and tasks). MTEB has a dataset and task checklist. For reference, below is the template they use.

---

## Checklist

- [ ] Run tests locally to make sure nothing is broken using `make test`. 
- [ ] Run the formatter to format the code using `make lint`. 

### Adding datasets checklist

**Reason for dataset addition**: ... 

- [ ] I have run the following models on the task (adding the results to the pr). These can be run using the `mteb -m {model_name} -t {task_name}` command.
  - [ ] `sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2`
  - [ ] `intfloat/multilingual-e5-small`
- [ ] I have checked that the performance is neither trivial (both models gain close to perfect scores) nor random (both models gain close to random scores).
- [ ] If the dataset is too big (e.g. >2048 examples), considering using `self.stratified_subsampling() under dataset_transform()`
- [ ] I have filled out the metadata object in the dataset file (find documentation on it [here](https://github.com/embeddings-benchmark/mteb/blob/main/docs/adding_a_dataset.md#2-creating-the-metadata-object)).
- [ ] Run tests locally to make sure nothing is broken using `make test`. 
- [ ] Run the formatter to format the code using `make lint`. 

### Adding a model checklist

 - [ ] I have filled out the ModelMeta object to the extent possible
 - [ ] I have ensured that my model can be loaded using
   - [ ] `mteb.get_model(model_name, revision_id)` and
   - [ ] `mteb.get_model_meta(model_name, revision_id)`
 - [ ] I have tested the implementation works on a representative set of tasks.

### CODE REVIEW

**Review by scopello — APPROVED** [review]
Looks good, thanks!

**Comment by jlkravitz** [comment]
anything from the DGEB checklist you wanna add?

**Review by ninjha01 — APPROVED** [review]
Two thoughts: 

1) This is totally a nit, but do we care about all of these distinctions? On my end, all I care about is breaking change/non breaking change + motivation for the PR.

```
- [ ] Bugfix
- [ ] Feature (e.g., including new dataset or model)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:
```

Perhaps contradictorily, I'd like to have a section for the reviewer to go through:

```
[ ] CI passes
[ ] docs updated
[ ] manual spotcheck
```


2) Perhaps off topic, but should we have a separate template for the actual results submission? Or could we fold that into this? I can create an issue and take this on if we think it's a good idea.

**Comment by jlkravitz** [comment]
> Two thoughts:
> 
> 1. This is totally a nit, but do we care about all of these distinctions? On my end, all I care about is breaking change/non breaking change + motivation for the PR.
> 
> ```
> - [ ] Bugfix
> - [ ] Feature (e.g., including new dataset or model)
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] CI related changes
> - [ ] Documentation content changes
> - [ ] Other... Please describe:
> ```
> 
> Perhaps contradictorily, I'd like to have a section for the reviewer to go through:
> 
> ```
> [ ] CI passes
> [ ] docs updated
> [ ] manual spotcheck
> ```
> 
> 2. Perhaps off topic, but should we have a separate template for the actual results submission? Or could we fold that into this? I can create an issue and take this on if we think it's a good idea.

On 1, I think my thought is that I would like to appropriately tag the commit, and these correspond 1:1 with the [conventional commit standard](https://www.conventionalcommits.org/en/v1.0.0/). I'm open to changing them or making them more aligned with this project, though. Thoughts?

Imo, CI passes: that's automated and required to merge.
docs updated: added
manual spotcheck: not sure if this adds anything?

On 2, I think we could fold into this. It seems like it can get annoying to have multiple PR templates. I'll merge this, and then we can iterate on it if that works!

**Comment by ninjha01** [comment]
works for me!

On Mon, Jul 15, 2024, at 12:58 PM, Joshua Kravitz wrote:
> 
> 
>> Two thoughts:
>> 
>>  1. This is totally a nit, but do we care about all of these distinctions? On my end, all I care about is breaking change/non breaking change + motivation for the PR.
>> `- [ ] Bugfix
>> - [ ] Feature (e.g., including new dataset or model)
>> - [ ] Code style update (formatting, local variables)
>> - [ ] Refactoring (no functional changes, no api changes)
>> - [ ] Build related changes
>> - [ ] CI related changes
>> - [ ] Documentation content changes
>> - [ ] Other... Please describe:
`
>> Perhaps contradictorily, I'd like to have a section for the reviewer to go through:
>> 
>> `[ ] CI passes
>> [ ] docs updated
>> [ ] manual spotcheck
`

**Pull request merged**
